name: Sync Fork

on:
  schedule:
    - cron: '0 6 * * *' # every day at 6am
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: suyashkumar
          base: main
          head: main
