name: build
on: [push, pull_request]
jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code 
      uses: actions/checkout@v1

    - name: Get dependencies
      run: | 
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin
            export REPO_PATH=$GOPATH/src/github.com/suyashkumar/dicom
            mkdir -p $GOBIN 
            export PATH=$PATH:/home/runner/go/bin
            mkdir -p $REPO_PATH
            cp -r $(pwd)/* $REPO_PATH 
            cd $REPO_PATH 
            go mod download


    - name: Build
      run: |
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin
            export REPO_PATH=$GOPATH/src/github.com/suyashkumar/dicom
            export PATH=$PATH:/home/runner/go/bin
            cd $REPO_PATH
            go build ./...
            make build-fast
   
    - name: Test
      run: |
            export GOPATH=$HOME/go
            export GOBIN=$GOPATH/bin 
            export REPO_PATH=$GOPATH/src/github.com/suyashkumar/dicom
            export PATH=$PATH:/home/runner/go/bin
            cd $REPO_PATH
            make test
  
    - name: Benchmark
      run: |
       export GOPATH=$HOME/go
       export GOBIN=$GOPATH/bin 
       export REPO_PATH=$GOPATH/src/github.com/suyashkumar/dicom
       export PATH=$PATH:/home/runner/go/bin
       go get golang.org/x/perf/cmd/benchstat
       echo "New Commit:"
       git log -1 --format="%H"
       cd $REPO_PATH
       go test -bench=. -count=5 > $HOME/new.txt
       cd $GITHUB_WORKSPACE
       git reset --hard HEAD
       git checkout $GITHUB_BASE_REF
       echo "Base Commit:"
       git log -1 --format="%H"
       rm -rf $REPO_PATH
       mkdir -p $REPO_PATH
       cp -r $(pwd)/* $REPO_PATH
       cd $REPO_PATH
       go test -bench=. -count=5 > $HOME/old.txt
       benchstat $HOME/old.txt $HOME/new.txt
       

